### ISSUE TITLE
current Dockerfile fails with default phoenix package.json dependencies

### ISSUE THREAD

**Issue by masterkain** [mirego/elixir-boilerplate#123]
This is the default, to keep the same version as the mix package:

_package.json_

```json
  "dependencies": {
    "phoenix": "file:../deps/phoenix",
    "phoenix_html": "file:../deps/phoenix_html",
    "phoenix_live_view": "file:../deps/phoenix_live_view",
```

result:

```
Step 5/42 : COPY assets assets
--
151 | ---> 9060e2a6e703
152 | Step 6/42 : RUN npm ci --prefix assets --no-audit --no-color --unsafe-perm
153 | ---> Running in e40b93be0361
154 | npm ERR! code ENOENT
155 | npm ERR! syscall open
156 | npm ERR! path /build/assets/node_modules/phoenix/package.json
157 | npm ERR! errno -2
158 | npm ERR! enoent ENOENT: no such file or directory, open '/build/assets/node_modules/phoenix/package.json'
159 | npm ERR! enoent This is related to npm not being able to find a file.
160 | npm ERR! enoent
```

**Comment by remi** [comment]
Hi Claudio,

I’m not sure what you mean by _default phoenix package.json dependencies_.

`phoenix` and `phoenix_html` are [already included](https://github.com/mirego/elixir-boilerplate/blob/master/assets/package.json#L19-L20) in `assets/package.json`:

```json
"phoenix": "phoenixframework/phoenix#v1.4.12",
"phoenix_html": "phoenixframework/phoenix_html#v2.13.3",
```

But you are correct that if you want to add `file:…` dependencies to your `assets/package.json`, you’ll have to modify the `Dockerfile` to copy any files or folders needed before `npm ci` is ran.

Hope this helps!

**Comment by masterkain** [comment]
for a moment I forgot that this is an entire project and not only the `Dockerfile` I was looking for, thanks 👍
