### ISSUE TITLE
Strict version requirements

### ISSUE THREAD

**Issue by mandarvaze** [mirego/elixir-boilerplate#13]
`make dependencies` fails saying `You are using Node.js 10.15.3 but the required version specified in package.json is 10.14.2`

If this is not a **strict** requirements, [package.json](https://github.com/mirego/elixir-boilerplate/blob/master/assets/package.json#L4) could be changed to `>=10.14.2` (I can make this simple change and send a PR, but want to understand if it would be OK)

**Comment by mandarvaze** [comment]
Similarly, I'm also getting `** (Mix) You're trying to run :long_term_bets on Erlang/OTP 21.2.7 but it has declared in its mix.exs file it supports only Erlang/OTP 21.3.3` when running `mix ecto.setup`

Unfortunately, latest version of erlang available via `brew` is 21.3.**2**

I wonder if there is a way to say Erlang Version >= 21.3 (or something)

**Comment by remiprev** [comment]
Hi @mandarvaze,

This is actually something that we will fix very soon.

Instead of freezing the whole version, we’ll freeze only the major and minor ones. Which means we’ll freeze something like Erlang `~> 21.3`, Elixir `~> 1.8` and Node.js `~> 10.15`.

Cheers!

**Comment by mandarvaze** [comment]
I cloned a fresh copy today, and I'm still getting `You are using Node.js 10.15.3 but the required version specified in package.json is ~10.14`
I'm not too familiar with package.json syntax, but looks like syntax `~>10.14` does not work for **node** (It may work for `npm`)

When I updated my local `assets/package.json` to `"node": ">=10.14"` the error went away.

**Comment by remiprev** [comment]
The error looks correct though, `10.15.X` does not match `~10.14`.

**Comment by mandarvaze** [comment]
@remiprev I wonder if this issue needs to be re-opened (I'm not sure whether that is possible) or create new issue, just so that this does not fall thru the crack.

**Comment by remiprev** [comment]
We want to freeze Node.js to `~10.14` because that’s the latest version provided by the stable Alpine Linux version we use in our Docker image.

However, we _could_ freeze Node.js to `^10.14` (which would allow `10.14.*`, `10.15.*`, `10.16.*`, etc. but not `11.*.*`).

I’ll reopen this issue and investigate if the change would cause unpleasant side-effects! :+1:
