### ISSUE TITLE
Is this a runtime ?

### ISSUE THREAD

**Issue by hopewise** [mirego/elixir-boilerplate#320]
Is this a runtime for Elixir on Google Cloud? what does it differ from https://github.com/GoogleCloudPlatform/elixir-runtime ?

**Comment by remi** [comment]
Hi @hopewise,

No this is not an Elixir runtime for Google Cloud 🤔

This is an Elixir project template to start new Elixir projects that can be deployed on any platform that supports Docker containers.

Hope that answers you question! ✌️
