### ISSUE TITLE
Add Absinthe GraphQL tooling

### ISSUE THREAD

**Issue by gcauchon** [mirego/elixir-boilerplate#34]
We have been using [GraphQL](https://graphql.org/) on every web projects for months, I think we should include the [Absinthe](https://absinthe-graphql.org/) setup in the _boilerplate_ to simplify scaffolding of upcoming Elixir projects.

**Comment by Sjoerrdd** [comment]
Any ideas when this is finished? I can't wait to use it ;)

**Comment by gcauchon** [comment]
> Any ideas when this is finished? I can't wait to use it ;)

@remiprev assigned himself to this issue 2 weeks ago, so my guess is it should land in a matter of days…

**Comment by remiprev** [comment]
Yes, I actually started it and the main issue was to know what to include and what to exclude 😄

Same thing for #5 and #58.

I should have something ready to review this week!
