### ISSUE TITLE
Add NewRelic performance monitoring

### ISSUE THREAD

**Issue by remi** [mirego/elixir-boilerplate#58]
We should add `new_relic_agent` and `new_relic_phoenix` since we’re using them in several of our applications.

**Comment by olivierbuffon** [comment]
IMO, I don't think `new_relic_phoenix` should be part of our default dependences. It's not officially maintained, the repo hasn't been really active lately and the infos returned are not always relevant especially when using stuff like GraphQL.

**Comment by remiprev** [comment]
> It's not officially maintained

The author works for New Relic so I think it’s safe to say that it’s a pretty safe package to use and future-proof. 😄 We’re also using the unofficial [`excoveralls`](https://github.com/parroty/excoveralls) package in the boilerplate.

> the infos returned are not always relevant

Are you referring to a specific bug in the package? If so, we should report it.

We’re using it in Elixir projects — that’s why I think it should be part of the boilerplate project if we add the `new_relic_agent` package. Same thing for `new_relic_absinthe` when #34 is completed.
