### ISSUE TITLE
Cannot run it on Google Cloud Run

### ISSUE THREAD

**Issue by pylebecq** [mirego/elixir-boilerplate#76]
Hello 👋 

Thank you for putting this repo on github, there are really nice things to learn from it.

I know this isn't really an issue with this repository that I'm writing now, it's more about asking for some help. I apologize in advance if you think this is inappropriate.

I'm trying to run some Phoenix application on Google Cloud Run and I'm having some difficulties for now. It worked a few weeks ago, and without even changing my image, it stopped working at some point.

While trying to search online on how to solve my problem, I found your video (https://www.youtube.com/watch?v=6Jo8WlWq-Fw) and this repo.

So I followed the video and tried to run this repo on Google Cloud Run. And the good news (well, I see that as a good news) is that this repo does not run either.

The bad part is that I don't have much to debug. This is the message that is displayed:

![image](https://user-images.githubusercontent.com/351471/64261677-2a336500-cf2d-11e9-9934-437d9994fbf6.png)

And as you can see, there is absolutely no logs written.

Maybe I did something wrong, because the boilerplate is different from what is shown in the video, so I may have missed an important step while commenting migrations and stuff like that in the code. I'm able to run it locally though, using `docker run --rm -it -e PORT=8080 -e SIGNING_SALT=abcde -e SECRET_KEY_BASE=V7SuPpXRJWyBtEP028aEFUzaVS1jnR0sMI6HwRVwzQRo9Z8fcV1HHB0OspZxetCA -p 8080:8080 boilerplate_cloud_run`. The health endpoint returns `{"status":"ok","version":"0.0.1"}`

But as I said, I cannot run my own project (which is a Phoenix application, without ecto) either. Can anyone who is used to run this on Google Cloud Run tell me if they can still successfully run it if they try to run it right now please?
That would be really helpful to me,  in order to know if something is wrong in my project and what I did with this repo, or if there is some kind of compatibility issue with Elixir / BEAM.

Best regards.

**Comment by renatorfr** [comment]
Hello @pylebecq! 👋 
I followed the same steps from my presentation for the current version of the boilerplate and I had the same error as you.
I'll check this further and I'll be back when find something :)

**Comment by pylebecq** [comment]
Hello @renatorfr 

Thank you for taking some time to verify if it was still working for you. It's very much appreciated.

I tried to contact Google's support, but still no answer for now. Because it's still in beta, the support seems to be limited, I guess we're on our own. 😓

**Comment by renatorfr** [comment]
Yep. That's one of the perks of using the service in beta :/
When I tried to deploy by command line, it stops at the "checking if the container is health" step. Since we don't provide a health URL to Google, I'm assuming it tries to request the `/` and waits for a `Ok 200`, the default is not returning a `Ok 200`, we need to add some values to some environment variables. If you check the file `.env.dev` you can see the ones asking to generate a hash with `mix phx.gen.secret`, now we have a `/` with status `Ok 200` but even with this, the deploy is still not working for me. I'll keep checking tonight.

**Comment by renatorfr** [comment]
Hi @pylebecq,

I succeeded in deploying the boilerplate in the current version in Google Cloud Run by the command line with the `gcloud` tool but for some reason that I still couldn't find, if I try to deploy the same container image using the GUI I have the error.
We have to give some values in some environment variables with this version.
If you want to try with the command line, this is the command that worked:
`gcloud beta run deploy --image gcr.io/{PROJECT_ID}/{IMAGE_NAME} --platform managed --set-env-vars SECRET_KEY_BASE={VALUE},SESSION_KEY={VALUE},SIGNING_SALT={VALUE},ERLANG_COOKIE={VALUE}`

To check and generate the values for the variables, you can follow the instructions in `.env.dev`. I'll keep digging to see if I found out why it's not working using the GUI, if I find something I'll post here :)

**Comment by pylebecq** [comment]
Hello @renatorfr 
I'm sorry I forgot to give some update on this.

I asked for help originally based on the report of someone trying to run on Google CloudRun some Elixir app I'm working on at Zenaton, and it worked for a long time, and when it stopped working they asked us for help, that's why I came here to also ask for help because I've never used CloudRun before and couldn't figure out what was wrong.

Anyway, it turns out that a few weeks later, they told me it started working again. We did not make any change. It started working again the same way it stopped working. So, I guess that was an issue on CloudRun itself, which was still in beta at that time.

So, I guess I'm just going to close this issue 🤷‍♂ 

Thanks again for taking the time to try things and give me some insights. It was much appreciated ❤️

**Comment by varunrau** [comment]
hi @renatorfr, I'm trying to play around with elixir-boilerplate and google cloud run. After following the steps in the video, I'm running into the same problem that @pylebecq saw. Any idea what's going on? I'm seeing issues when running the command you posted as well as deploying through the UI.
