### ISSUE TITLE
Make the project available as Aqua template

### ISSUE THREAD

**Issue by Virviil** [mirego/elixir-boilerplate#9]
It seems that initializing the project can be done a bit more handy with [Aqua](https://github.com/aquapm/aqua) template engine. It's generaly created for this purposes.

With small changes the project can be boilerplated using

```
mix aqua new boilerplate MyApp
```

with optional **docker** (for example):

```
mix aqua new boilerplate MyApp --no-docker
```

With auto predefined Elixir versions, and better discovered `project_name` changes.

If it's possible - I can do this for the project, just want to be sure that it has any sence.

**Comment by simonprev** [comment]
Looks like the Aqua project is not being maintained anymore (last commit 3 years ago). If the changes you want to do makes sense without Aqua you can still send a PR 😃
